spring:
  application:
    name: week3-4
  datasource:
    url: jdbc:postgresql://localhost:5432/week3-4_DB
    username: postgres
    password: newpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9292


